// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: sessions.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 64 lowercase hex chars = sha256(raw_token). The raw token never appears here.
	TokenHash     string `protobuf:"bytes,1,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

type ResolveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ResolveResponse_Session
	//	*ResolveResponse_NotFound
	Outcome       isResolveResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetOutcome() isResolveResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ResolveResponse) GetSession() *Session {
	if x != nil {
		if x, ok := x.Outcome.(*ResolveResponse_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ResolveResponse) GetNotFound() *NotFound {
	if x != nil {
		if x, ok := x.Outcome.(*ResolveResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

type isResolveResponse_Outcome interface {
	isResolveResponse_Outcome()
}

type ResolveResponse_Session struct {
	Session *Session `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type ResolveResponse_NotFound struct {
	// unknown, expired, and revoked are deliberately indistinguishable
	NotFound *NotFound `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

func (*ResolveResponse_Session) isResolveResponse_Outcome() {}

func (*ResolveResponse_NotFound) isResolveResponse_Outcome() {}

type Session struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Principal            string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	ExpiresAtUnixSeconds int64                  `protobuf:"varint,2,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	TenantId             string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Session) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

func (x *Session) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type NotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFound) Reset() {
	*x = NotFound{}
	mi := &file_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFound) ProtoMessage() {}

func (x *NotFound) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFound.ProtoReflect.Descriptor instead.
func (*NotFound) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{3}
}

var File_sessions_proto protoreflect.FileDescriptor

const file_sessions_proto_rawDesc = "" +
	"\n" +
	"\x0esessions.proto\x12\x02am\"/\n" +
	"\x0eResolveRequest\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x01 \x01(\tR\ttokenHash\"r\n" +
	"\x0fResolveResponse\x12'\n" +
	"\asession\x18\x01 \x01(\v2\v.am.SessionH\x00R\asession\x12+\n" +
	"\tnot_found\x18\x02 \x01(\v2\f.am.NotFoundH\x00R\bnotFoundB\t\n" +
	"\aoutcome\"{\n" +
	"\aSession\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x125\n" +
	"\x17expires_at_unix_seconds\x18\x02 \x01(\x03R\x14expiresAtUnixSeconds\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\n" +
	"\n" +
	"\bNotFound2D\n" +
	"\x0eSessionService\x122\n" +
	"\aresolve\x12\x12.am.ResolveRequest\x1a\x13.am.ResolveResponseB\x04Z\x02./b\x06proto3"

var (
	file_sessions_proto_rawDescOnce sync.Once
	file_sessions_proto_rawDescData []byte
)

func file_sessions_proto_rawDescGZIP() []byte {
	file_sessions_proto_rawDescOnce.Do(func() {
		file_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)))
	})
	return file_sessions_proto_rawDescData
}

var file_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sessions_proto_goTypes = []any{
	(*ResolveRequest)(nil),  // 0: am.ResolveRequest
	(*ResolveResponse)(nil), // 1: am.ResolveResponse
	(*Session)(nil),         // 2: am.Session
	(*NotFound)(nil),        // 3: am.NotFound
}
var file_sessions_proto_depIdxs = []int32{
	2, // 0: am.ResolveResponse.session:type_name -> am.Session
	3, // 1: am.ResolveResponse.not_found:type_name -> am.NotFound
	0, // 2: am.SessionService.resolve:input_type -> am.ResolveRequest
	1, // 3: am.SessionService.resolve:output_type -> am.ResolveResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sessions_proto_init() }
func file_sessions_proto_init() {
	if File_sessions_proto != nil {
		return
	}
	file_sessions_proto_msgTypes[1].OneofWrappers = []any{
		(*ResolveResponse_Session)(nil),
		(*ResolveResponse_NotFound)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessions_proto_goTypes,
		DependencyIndexes: file_sessions_proto_depIdxs,
		MessageInfos:      file_sessions_proto_msgTypes,
	}.Build()
	File_sessions_proto = out.File
	file_sessions_proto_goTypes = nil
	file_sessions_proto_depIdxs = nil
}
